// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhsGSVP-5GDYD76Zr6RvSVJVtPxi0BqtM',
    appId: '1:914650984803:web:0ff1753e281ee5b840e356',
    messagingSenderId: '914650984803',
    projectId: 'westgate-pest-control',
    authDomain: 'westgate-pest-control.firebaseapp.com',
    storageBucket: 'westgate-pest-control.appspot.com',
    measurementId: 'G-8Y25ESMWJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo3_I9nnzQECHDbb1jlCclLSZbzmmZqhM',
    appId: '1:914650984803:android:f2d935fb173ca07d40e356',
    messagingSenderId: '914650984803',
    projectId: 'westgate-pest-control',
    storageBucket: 'westgate-pest-control.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzNfQ5E9MNey6piHV13z1jWpcinGkfjo0',
    appId: '1:914650984803:ios:b4206d1d300bc24e40e356',
    messagingSenderId: '914650984803',
    projectId: 'westgate-pest-control',
    storageBucket: 'westgate-pest-control.appspot.com',
    iosBundleId: 'com.example.westgatePestControlWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzNfQ5E9MNey6piHV13z1jWpcinGkfjo0',
    appId: '1:914650984803:ios:b4206d1d300bc24e40e356',
    messagingSenderId: '914650984803',
    projectId: 'westgate-pest-control',
    storageBucket: 'westgate-pest-control.appspot.com',
    iosBundleId: 'com.example.westgatePestControlWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhsGSVP-5GDYD76Zr6RvSVJVtPxi0BqtM',
    appId: '1:914650984803:web:01b46ca9f8644c6d40e356',
    messagingSenderId: '914650984803',
    projectId: 'westgate-pest-control',
    authDomain: 'westgate-pest-control.firebaseapp.com',
    storageBucket: 'westgate-pest-control.appspot.com',
    measurementId: 'G-SEKTKTRZRG',
  );
}
